### ISSUE TITLE
Kotlin issues

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud-samples/spring-cloud-contract-samples#177]
hey @shanman190, I still can't build the Kotlin based projects. I've also added github actions that will finally run the samples in a visible way.

```
11:09:22 Building [producer_webflux_security] skipping tests? [false] after prepare for workshops? [false]
11:09:22 
11:09:22 
11:09:22 + cd producer_webflux_security
11:09:22 + [[ false == \t\r\u\e ]]
11:09:22 + [[ false == \t\r\u\e ]]
11:09:22 + ./gradlew clean build publishToMavenLocal --stacktrace --refresh-dependencies --console=plain
11:09:22 To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.7/userguide/gradle_daemon.html.

11:09:23 Daemon will be stopped at the end of the build stopping after processing

11:09:38 
11:09:38 > Configure project :
11:09:38 Boot Version [2.4.0], Cloud version [2020.0.0-SNAPSHOT], Contract version [3.0.0-SNAPSHOT]

11:09:39 Spring Cloud Contract Verifier Plugin: Falling back to legacy contracts directory in 'test' source set. Please switch to 'contractTest' source set as this will be removed in a future release.
11:09:39 Spring Cloud Contract Verifier Plugin: Falling back to legacy contracts directory in 'test' source set. Please switch to 'contractTest' source set as this will be removed in a future release.
11:09:39 
11:09:39 > Task :clean UP-TO-DATE

11:09:48 > Task :compileKotlin
11:09:48 > Task :compileJava NO-SOURCE
11:09:48 > Task :compileGroovy NO-SOURCE
11:09:48 > Task :processResources
11:09:48 > Task :classes
11:09:48 > Task :bootJarMainClassName
11:09:49 > Task :bootJar
11:09:49 > Task :inspectClassesForKotlinIC
11:09:49 > Task :jar SKIPPED
11:09:49 
11:09:49 > Task :copyContracts
11:09:49 Spring Cloud Contract Verifier Plugin: Falling back to legacy contracts directory in 'test' source set. Please switch to 'contractTest' source set as this will be removed in a future release.

11:09:49 
11:09:49 > Task :generateClientStubs
11:09:49 > Task :verifierStubsJar
11:09:49 > Task :assemble

11:09:51 
11:09:51 > Task :compileTestKotlin
11:09:51 Errors occurred while build effective model from /opt/jenkins/.gradle/caches/modules-2/files-2.1/com.sun.xml.bind/jaxb-osgi/2.2.10/c926a537af564ec047ec6308df1d0d2a03364a86/jaxb-osgi-2.2.10.pom:
11:09:51     'dependencyManagement.dependencies.dependency.systemPath' for com.sun:tools:jar must specify an absolute path but is ${tools.jar} in com.sun.xml.bind:jaxb-osgi:2.2.10
11:09:52 
11:09:52 > Task :compileTestJava NO-SOURCE
11:09:52 > Task :compileTestGroovy SKIPPED
11:09:52 > Task :processTestResources
11:09:52 > Task :testClasses
11:09:52 > Task :test
11:09:52 > Task :compileContractTestKotlin NO-SOURCE
11:09:53 > Task :generateContractTests
11:09:53 > Task :compileContractTestJava FAILED
11:09:53 
11:09:53 FAILURE: Build failed with an exception.
11:09:53 
11:09:53 * What went wrong:
11:09:53 A problem was found with the configuration of task ':compileContractTestJava' (type 'JavaCompile').
11:09:53 > Directory 'producer_webflux_security/build/classes/kotlin/contractTest' specified for property 'compileContractTestKotlinOutputClasses' does not exist.
11:09:53 
11:09:53 * Try:
11:09:53 Run with --info or --debug option to get more log output. Run with --scan to get full insights.
11:09:53 
11:09:53 * Exception is:
11:09:53 org.gradle.internal.execution.WorkValidationException: A problem was found with the configuration of task ':compileContractTestJava' (type 'JavaCompile').
11:09:53 	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:71)
11:09:53 	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:78)
11:09:53 	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:78)
11:09:53 	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
11:09:53 	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:39)
11:09:53 	at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:40)
11:09:53 	at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:28)
11:09:53 	at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
11:09:53 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:187)
11:09:53 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:179)
11:09:53 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
11:09:53 	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
11:09:53 	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
11:09:53 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
11:09:53 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
11:09:53 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
11:09:53 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
11:09:53 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
11:09:53 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
11:09:53 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
11:09:53 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
11:09:53 	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
11:09:53 	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
11:09:53 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
11:09:53 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
11:09:53 	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
11:09:53 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
11:09:53 	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
11:09:53 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
11:09:53 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
11:09:53 	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
11:09:53 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
11:09:53 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
11:09:53 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
11:09:53 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
11:09:53 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
11:09:53 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
11:09:53 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
11:09:53 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
11:09:53 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
11:09:53 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
11:09:53 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
11:09:53 Caused by: org.gradle.api.InvalidUserDataException: Directory '/opt/jenkins/data/workspace/spring-cloud-contract-samples-build-gradle-only-jdk11-3.0.x-e2e/producer_webflux_security/build/classes/kotlin/contractTest' specified for property 'compileContractTestKotlinOutputClasses' does not exist.
11:09:53 	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:71)
11:09:53 	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:78)
11:09:53 	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:78)
11:09:53 	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
11:09:53 	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:39)
11:09:53 	at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:40)
11:09:53 	at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:28)
11:09:53 	at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
11:09:53 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:187)
11:09:53 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:179)
11:09:53 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
11:09:53 	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
11:09:53 	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
11:09:53 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
11:09:53 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
11:09:53 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
11:09:53 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
11:09:53 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
11:09:53 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
11:09:53 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
11:09:53 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
11:09:53 	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
11:09:53 	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
11:09:53 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
11:09:53 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
11:09:53 	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
11:09:53 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
11:09:53 	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
11:09:53 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
11:09:53 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
11:09:53 	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
11:09:53 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
11:09:53 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
11:09:53 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
11:09:53 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
11:09:53 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
11:09:53 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
11:09:53 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
11:09:53 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
11:09:53 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
11:09:53 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
11:09:53 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
```

**Comment by shanman190** [comment]
@marcingrzejszczak, ok. This is probably still blocked by the other PR that we have in sc-contract that is still open. We could potentially re-comment out the Kotlin tests until that has been merged. WDYT?

**Comment by marcingrzejszczak** [comment]
Yeah that's what we did https://github.com/spring-cloud-samples/spring-cloud-contract-samples/commit/38948a1287ee6a7b3d7f3d5d374e487bf97aab34 . We've managed to have green gradle samples now, thanks to @OlgaMaciaszek ! We can start uncommenting the samples one by one I guess.

**Comment by shanman190** [comment]
Sweet. Thanks, @OlgaMaciaszek! 

Yeah, I'm good with uncommenting one by one. I'll wait to add any of them until the sc-contract or gets merged.

**Comment by shanman190** [comment]
@marcingrzejszczak, I think this is now resolved, would you agree?

**Comment by marcingrzejszczak** [comment]
Yup, fixed via https://github.com/spring-cloud-samples/spring-cloud-contract-samples/commit/925af992636c9363d0b5200d73ad15408c16d84e
