### ISSUE TITLE
spring-cloud-stub-runner issue with downloading pact contracts

### ISSUE THREAD

**Issue by naushadamin** [spring-cloud-samples/spring-cloud-contract-samples#264]
**Describe the bug**
I've a consumer project which published a Pact contract to a remote pact repo successfully. Now I am trying to auto-generate the verifier test in Producer project using spring-cloud-contract-pact project. I added the following bits in by build.gradle file to configure test generation:

contractsMode = "REMOTE"
    	// Base package for generated tests
    	baseClassForTests = "somebaseclass"
    	contractRepository {
    		repositoryUrl = "pact://https://namin.pactflow.io"
    	}

When I build my project it fails. Upon further investigation, I found the copyContract gradle task is failing with the following:

2021-06-23T07:01:10.922-0400 [DEBUG] [org.springframework.cloud.contract.stubrunner.StubRunnerOptions] File not found
java.io.FileNotFoundException: class path resource [pact://https://namin.pactflow.io] cannot be resolved to URL because it does not exist
	at org.springframework.core.io.ClassPathResource.getURL(ClassPathResource.java:202)
	at org.springframework.core.io.AbstractResource.getURI(AbstractResource.java:123)
	at org.springframework.cloud.contract.stubrunner.StubRunnerOptions.getStubRepositoryRootAsString(StubRunnerOptions.java:263)
	at org.springframework.cloud.contract.stubrunner.AetherStubDownloader.remoteRepositories(AetherStubDownloader.java:144)
	at org.springframework.cloud.contract.stubrunner.AetherStubDownloader.<init>(AetherStubDownloader.java:83)
	at org.springframework.cloud.contract.stubrunner.AetherStubDownloaderBuilder.build(AetherStubDownloaderBuilder.java:38)

I am following the example from your sample producer-pact directory here. Not sure what needs to be configured to resolve the issue. Also, I noticed that currently username/password based authentication is supported. However, I have configured authentication to my pact repo using bearer token. Is token based authentication supported?

**Comment by marcingrzejszczak** [comment]
That's `DEBUG` you shouldn't worry about this. You can debug the Pact downloader and see if the connection is occurring properly.

**Comment by naushadamin** [comment]
running 'gradlew build' generates the below error:

Execution failed for task ':copyContracts'.
> Remote repositories for stubs are not specified and work offline flag wasn't passed

**Comment by naushadamin** [comment]
Getting back on this one. Upon further investigations, the below stacktrace results in an empty string being returned as remote repository which generates the IllegalStateException with 'Remote repositories for stubs are not specified and work offline flag wasn't passed' :
java.io.FileNotFoundException: class path resource [pact://https://namin.pactflow.io] cannot be resolved to URL because it does not exist
	at org.springframework.core.io.ClassPathResource.getURL(ClassPathResource.java:202)
	at org.springframework.core.io.AbstractResource.getURI(AbstractResource.java:123)
	at org.springframework.cloud.contract.stubrunner.StubRunnerOptions.getStubRepositoryRootAsString(StubRunnerOptions.java:263)
	at org.springframework.cloud.contract.stubrunner.AetherStubDownloader.remoteRepositories(AetherStubDownloader.java:144)
	
In looking at the above trace, my question is why the framework is trying to look for a classpath resource based on the url? Am I missing some dependencies in my classpath so runtime is using an incorrect implementation? I am blocked at this point. Also I need to know if the framework will support token based authentication. Thanks in advance!

**Comment by marcingrzejszczak** [comment]
It tries to use various stub downloaders. If you scroll the logs up you will see that the PACT one failed. We do support token based auth in 3.0.x https://github.com/spring-cloud/spring-cloud-contract/blob/v3.0.3/spring-cloud-contract-tools/spring-cloud-contract-pact/src/main/java/org/springframework/cloud/contract/stubrunner/PactStubDownloaderBuilder.java#L293

**Comment by marcingrzejszczak** [comment]
Have you added spring-cloud-contract-pact to the plugin's classpath?

**Comment by marcingrzejszczak** [comment]
Also what is token? We don't provide such a field to configure the Gradle plugin

**Comment by naushadamin** [comment]
> Also what is token? We don't provide such a field to configure the Gradle plugin

Do you have any documentation on how to to configure the token value? I was looking that source reference and your documentation here https://docs.spring.io/spring-cloud-contract/docs/3.0.0-SNAPSHOT/reference/htmlsingle/#how-to-use-pact-broker and assumed I can set the token attribute along with repo url. If that is not correct then please provide example of how to set the value. Thanks

**Comment by naushadamin** [comment]
Any update on this issue? I am unable to determine how to correctly set auth token for pact broker.

**Comment by marcingrzejszczak** [comment]
This is how we set up the pact properties https://github.com/spring-cloud/spring-cloud-contract/blob/main/spring-cloud-contract-tools/spring-cloud-contract-pact/src/main/java/org/springframework/cloud/contract/stubrunner/PactStubDownloaderBuilder.java#L313-L358

You can try passing a system property `-Dpactbroker.auth.token` or a system property `-Dstubrunner.properties.pactbroker.auth.token` or an env var `STUBRUNNER_PROPERTIES_PACTBROKER_AUTH_TOKEN` or pass those via the `properties` annotation method oif the `@AutoConfigureStubRunner` annotation (https://github.com/spring-cloud/spring-cloud-contract/blob/dc9b19be6dbbb6d9654fa582e8ef14877ee29a16/spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/spring/AutoConfigureStubRunner.java#L132) or properties of the JUnit extension in the same fashion

**Comment by naushadamin** [comment]
I've attempted to set the system property -Dpactbroker.auth.token  as following:

1.` /gradlew buiild -Dpactbroker.auth.token="sometoken"`
2. in build.gradle as following:
```
test {
systemProperty "pactbroker.auth.token", "sometoken"
}
```

I also attempted to include in contractProperties as following:

`contractsProperties(["pactbroker.auth.token":"sometoken"])` 

However, I am still getting 401 in response back from the broker. This is what I gathered from DEBUG log what is being passed:

`2021-09-14T15:47:41.225-0400 [DEBUG] [org.springframework.cloud.contract.stubrunner.AetherStubDownloader] Will be resolving versions for the following options: [StubRunnerOptions{minPortValue=10000, maxPortValue=15000, stubRepositoryRoot='URL [https://namin.pactflow.io/pacts/provider/siteapi/consumer/siteapi-consumer/version/1.0.0.devlocal]', stubsMode='REMOTE', stubsClassifier='stubs', dependencies=[], stubIdsToPortMapping={}, username='****', password='', stubRunnerProxyOptions='null', stubsPerConsumer='false', httpServerStubConfigurer='class org.springframework.cloud.contract.stubrunner.HttpServerStubConfigurer$NoOpHttpServerStubConfigurer'}]`

**Comment by shanman190** [comment]
This is the same issue as gh-178.
